version: '2'

services:
  example_data:
    container_name: travshacl_example_data
    image: prohde/virtuoso-opensource-7:7.2.13-alpine
    volumes:
      - ./data/raw:/database/toLoad
      - ./data/virtuoso:/database
    mem_limit: 2g
    ports:
      - '9090:8890'
    networks:
      - travshacl

  example_engine:
    container_name: travshacl_example_engine
    image: sdmtib/travshacl:latest
    volumes:
      - ./shapes:/shapes
    mem_limit: 4g
    ports:
      - '9091:5000'
    networks:
      - travshacl
    depends_on:
      - example_data

networks:
  travshacl:
    driver: bridge
